spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://82.156.87.213:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: guest
    password: guest
    host: 82.156.87.213
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 82.156.87.213
    database: 0
    port: 6379
  #    password: 123
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://82.156.87.213/
logging:
  level:
    root: debug
security:
  basic:
    enabled: true
    path: /swagger-ui.html
  user:
    name: admin
    password: 123456
swagger:
  enable: true